orocos-toolchain/ocl

timer/TimerComponent.cpp

Fixes #23.
This patch requires https://github.com/orocos-toolchain/rtt/pull/76.

Implemented TimerComponent::wait() and TimerComponent::waitFor()

---

taskbrowser/TaskBrowser.cpp

Tab completion was not possible for members of properties of type propertybag. This PR allow this.
Signed-off-by: Ruben Smits <ruben.smits@intermodalics.eu>

taskbrowser: allow completion for members of properties of type PropertyBag

---

deployment/DeploymentComponent.cpp
deployment/DeploymentComponent.hpp

This pull request adds the `DefaultWaitPeriodPolicy` property to the DeploymentComponent to influence the wait period policy of newly created activities. I also added an operation `setWaitPeriodPolicy(name, policy) to reset the wait period policy of any component after creation.
From fosi.h:
```cpp
#define ORO_WAIT_ABS 0 /** rtos_task_wait_period may wait less than the duration required to pad the period to 
catch-up with overrun timesteps (wait according to an absolute timeline) */
#define ORO_WAIT_REL 1 /** rtos_task_wait_period will always pad the current timestep to the desired period, 
regardless of previous overruns (wait according to a relative timeline) */
```
The constants `ORO_WAIT_ABS` and `ORO_WAIT_REL` have been added to the RTT::types::GlobalsRepository in …

deployment: added property and an operation to influence the wait period policy of periodic activities

---

lua/modules/rttros.lua

The rtt_rospack package (and most other plugins provided by rtt_ros_integration) adds its operation `find` to the global service named `ros`.

Fixed underlying service call to package rtt_rospack in rtt_ros.find_rospack()

---

deployment/DeploymentComponent.cpp
deployment/tests/deployment.cpf
deployment/tests/main.cpp

This PR adds a new element to the XML deployment file for setting the default connection policy, if OCL is compiled against a version of RTT that has a default policy (see orocos-toolchain/rtt#114). The values of the default connection policy are copied over to every new ConnPolicy instance created.
The patch does not introduce a new XML tag, but a ConnPolicy element with the special name "Default" is interpreted as the new process-wide default policy. There is a small risk that this name is already in use to name connections in some existing XML files, but even then this patch would not necessarily break the deployment except that all other connections without an explicit ConnPolicy element would also use this default ConnPolicy.

Read default connpolicy from deployment XML file

---

deployment/DeploymentComponent.cpp
deployment/DeploymentComponent.hpp

Added a new method `DeploymentComponent::waitForSignals()` to wait for multiple signals.
The default `waitForInterrupt()` implementation installs three handlers for SIGINT, SIGTERM and SIGHUP now. SIGINT is typically only used to catch Ctrl-C on stdin, while external processes usually send the SIGTERM signal to request a shutdown (like the init daemon, roslaunch etc.).

deployer: Also terminate cleanly on SIGTERM and SIGHUP

---

bin/deployer-corba.cpp
bin/deployer.cpp
deployment/DeploymentComponent.hpp

For backwards-compatibility there are still small differences between running in daemon mode, rttscript and running a deployer without a tty:
Main process exits after the deployment. One of the scripts need to block or the whole process terminates.
It should be noted that the deployer is still not a "daemon" process in the usual sense, as it does not detach from the current session (see See http://codingfreak.blogspot.com/2012/03/daemon-izing-process-in-linux.html).
I would consider the daemon mode as broken as long as the deployer does not fork and wait for a signal after all deployment scripts have been run successfully, even if waitForInterrupt() is not explicitly called.
Actually the same as `deployer --daemon`, but in this case it might be fine to terminate after all scripts run …

deployer: do not run a TaskBrowser if the deployer was invoked without a tty input

---

deployment/DeploymentComponent.cpp

Because the DeploymentComponent overrides the loadService operation and the name of the deployer might not be known, the operations which translate a string into a TaskContext should accept "this" as an alias for the DeploymentComponent itself. This is in line with the usage of the "this" keyword in RTT scripting.
Use case:
```
import("rtt_rosdeployment")
loadService("this", "rosdeployment")
```

deployment: accept name "this" as an alias for the DeploymentComponent in arguments

---

deployment/DeploymentComponent.cpp

The `ComponentLoader::Release()` command was added in b91a085d798d153bf6fad2d0d647495d7d06e664, but the class' definition and implementation has been moved from OCL to RTT in 1a19d57ca4d9b0b137150cca5d3ff10d327e8c32.
There could be multiple DeploymentComponent instances in a single process, so destruction of one of them should not cleanup the global ComponentLoader. The `RTT::os::StartStopManager` already takes care of this. See https://github.com/orocos-toolchain/rtt/blob/master/rtt/deployment/ComponentLoader.cpp#L275.

deployment: do not release the ComponentLoader during destruction of the DeploymentComponent

---

lua/modules/rttlib.lua

Attributes are owned by the TaskContext and `TaskContext::removeAttribute()` or the respective Lua wrapper already destroys the instance returned by `TaskContext::getAttribute()`. The additional `attr:delete()` command triggers a segfault if the component has at least one attribute. The implementation of attributes is different from ports and properties with that respect, which are not cloned when they are added to the component interface.
On the other hand while adding attributes the instance created by Lua in `Attribute_new()` should be destroyed after it has been cloned and added to the TaskContext or `TaskContext_addAttribute()` must exchange the instance pointer in the Lua stack with the clone (not sure if this is possible).

lua: fixed cleanup of TaskContexts with the tc_cleanup function

---

deployment/DeploymentComponent.cpp

The component is added to a group only when it is loaded, not when a service is added or changed.
Use case:
- first configuration xml loads two components A and B.  B has a slaveActivity while A has a master Activity.
- second configuration xml loads other components and add a port to the component A. Therefore A is moved to the second group.
When shutting down the Deployer unload groups in the reverse order.
With the current logic A is unloaded when the second group is unloaded but B that is a slaveActivity is unloaded only when the first group is unloaded.

change deployer components group assignment logic

---

CMakeLists.txt
env-hooks/00.ocl-lua.sh.in

The env-hook adds the installation folders of the ocl-lua modules to the LUA_PATH/LUA_CPATH environment variables.
The scripts in etc/orocos/OROCOS_TARGET/profile.de will be sourced in lexical order by a new [setup.sh](https://github.com/meyerj/orocos_toolchain/blob/installation-script/setup.sh)
script located in the orocos_toolchain repository.

env-hooks: install env-hook for ocl-lua to etc/orocos/OROCOS_TARGET/profile.d

---

helloworld/CMakeLists.txt

I got the following compile error without this: `/home/rsmits/my_ws/src/orocos_toolchain/ocl/helloworld/HelloWorld.cpp:8:25: fatal error: rtt/os/main.h: No such file or directory`

Use orocos macro for helloworld executable

---

logging/Category.cpp
logging/Category.hpp
logging/LoggingService.cpp
logging/LoggingService.hpp

Add additional debug output.
Support setting/getting the logging level on a category.
Support creating a category when connecting it to an appender, just as one is created when setting additivity or the logging level.
Add an optimization to only write to a log port that is connected.

Minor logging fixes

---

bin/cdeployer.cpp
bin/deployer-corba.cpp
bin/deployer.cpp
deployment/DeploymentComponent.cpp
deployment/DeploymentComponent.hpp

The existing "check" approach calls loadComponents(file), which loaded all components from "file" into the next group, and then called configureComponents(), which configured *all* groups. This results in configuring components in some layers multiple times, if multiple files are loaded. e.g.
- kickStart(file1);
- kickStart(file2);
results in
- load components from file 1
- configure components from file 1
- load components from file 2
- configure components from file 1 // BAD!
- configure components from file 2
The fix is to use the internal load/configure/start functions that know about groups, and which only load/configure/start the components of the current group. This effectively needs a kickStart() that knows whether the user wants to start components or not (which is the only net …

Prevent double-configure issues when checking deployments

---

bin/cdeployer.cpp
bin/deployer-corba.cpp
bin/deployer-funcs.cpp
bin/deployer-funcs.hpp
bin/deployer.cpp
deployment/DeploymentComponent.cpp
deployment/DeploymentComponent.hpp

Refactor the TLSF code in the three (3) deployers.
Add code to dump TLSF statistics

Refactor deployers

---

deployment/DeploymentComponent.cpp
timer/TimerComponent.cpp
timer/TimerComponent.hpp

Make it easier to trace threads to their associated component(s)
- Correctly pass component names to activities
- Separate the name of the TimerComponent internal thread from the parent component's thread.

Fix thread naming

---

deployment/DeploymentComponent.cpp

This PR adds the possibility to refer to the Deployer using the keyword `this` independently of its name when using xml files.
Example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "cpf.dtd">
<properties>
<simple name="Path" type="string">
<value>lib/orocos</value>
</simple>
<simple name="Import" type="string"><value>kdl_typekit</value></simple>
<struct name="this" type="">
<struct name="Properties" type="PropertyBag">
<simple name="shutdownWait_ms" type="long"><value>50</value></simple>
<simple name="shutdownTotalWait_ms" type="long"><value>2000</value></simple>
</struct>
</struct>
</properties>
```
Signed-off-by: Luca Magnabosco <luca@intermodalics.eu>

deployment::DeploymentComponent add keyword this to refer to Deployer

---

taskbrowser/CMakeLists.txt
taskbrowser/TaskBrowser.cpp
taskbrowser/TaskBrowser.hpp

This is a fix for a regression bug reported in #64 and introduced in https://github.com/orocos-toolchain/ocl/pull/7 if the task browser is compiled with [editline](http://thrysoee.dk/editline/) support.
Signal handling is not available in editline and hence
- `OCL::TaskBrowser::rl_received_signal`
- `OCL::TaskBrowser::rl_signal_handler()` and
- `OCL::TaskBrowser::rl_getc()`
must not be defined.
Also fixes `taskbrowser/CMakeLists.txt` which did not check whether editline is actually installed if `NO_GPL` is set but `TASKBROWSER_EDITLINE` is not. Both flags result in compilation with editline support.

taskbrowser: fix editline support

---

deployment/DeploymentComponent.cpp
deployment/DeploymentComponent.hpp
deployment/tests/deployment.cpf
deployment/tests/main.cpp

This PR is picking some commits from @snrkiwi's fork.
The deployer ignores unknown ports in a first pass to create connections and tries again after the configure step, where errors would result in a failure. This allows to create and connect dynamically from the `configureHook().
This is the most important commit message from https://github.com/meyerj/ocl/commit/576c34e40a9fc4dc84a71b08176df595bb0b3877:
> deployment: Support multiple passes of connecting data ports
> The first pass must be tolerant of connections that only have one
> port currently - future ports may complete this connection.
> 
> So during the first pass, when loading components only ports that
> are compiled in to a component (ie created in the component's
> constructor), it is acceptable to have a connection with only …

Support connecting dynamically created ports

---

deployment/DeploymentComponent.cpp
timer/TimerComponent.cpp
timer/TimerComponent.hpp

This PR is picking some commits from @snrkiwi's fork.
It passes the thread name from xml deployment configs to the activity instances created for the components, which is especially useful for debugging in combination with https://github.com/orocos-toolchain/rtt/pull/128 and follow-up patches.
Commit messages:
> deployment: Fix passing component name to all activities
> Without this the thread name is set to "FileDescriptorActivity", etc, which
> is useless when multiple of each activity type are present in the deployment.
> The fix is to pass the component name to the activity class constructor, the
> same as with the other Activity derived classes.
> WARNING PeriodicActivity does not support a name, so nothing to do there.
> timer: Name the underlying Timer activity/thread
> Currently …

Fix thread naming for components deployed from xml configurations

---

bin/cdeployer.cpp
bin/deployer-corba.cpp
bin/deployer.cpp

This pull request is a collection of three functionally independent older commits, but they are all related to the deployer executables and its variants cdeployer and deployer-corba and would cause merge conflicts if applied in arbitrary order.
- Makes sure that `shutdownDeployment()` is called and the DeploymentComponent is destroyed before the call to `ShutdownOrb()` and `DestroyOrb()`. This allows the components to communicate with remote peers during their stop and cleanup transitions and to cleanly disconnect all connections.
- GitHub has a hard time to format this patch correctly in normal view because indentation changed for large parts of the file. In fact, only very few lines were changed, see https://github.com/orocos-toolchain/ocl/commit/6f2496a4872f550d374cf83c05672ddb2ce9ee43? …

deployer: cleanup and unify CORBA deployers and fix shutdown and error reporting

---

reporting/ReportingComponent.cpp
reporting/ReportingComponent.hpp

Quickfix for [this issue](https://github.com/orocos-toolchain/ocl/issues/67). 
It allows user to select more robust but slow decomposition procedure to avoid incorrect Reporter output.

ReportingComponent: ComplexDecompose parameter

---

lua/modules/rttlib.lua
lua/rtt.cpp

These changes fixes the following problem. If in lua console user tries to display Service interface and one of Operations contains `unknown_t` as parameter then lua exception occurs.  
`TaskContext` interfaces are displayed properly so I modified `service2str` accordingly.

Fix to the problem with displaying service intreface with `unknown_t`

---

ocl/OSService.cpp

Follow-up on https://github.com/orocos-toolchain/ocl/pull/51: Added operation `millisleep(unsigned int milliseconds)` to suspend execution of the calling thread by `milliseconds` milliseconds.

ocl: Added millisleep operation to the os service

---

lua/tlsf.c

Fix for https://github.com/orocos-toolchain/orocos_toolchain/issues/31
Compiles now on Ubuntu 18.04 by casting to be safe

Ensure u32 for c++14

---

bin/cdeployer.cpp
bin/deployer-corba.cpp
bin/deployer.cpp

This is a regression from https://github.com/orocos-toolchain/ocl/pull/74 (https://github.com/orocos-toolchain/ocl/pull/74/commits/6d10d0977e8d6a29d68bcdf24811acd4f271f466), which removed the `using namespace std` directive, but was picked from a branch were https://github.com/orocos-toolchain/ocl/pull/57 was already applied. The latter moved the tlsf log output from the individual deployers to a centralized class in `deployer-funcs.cpp` and therefore did not require the using namespace directive anymore.

bin: add missing std namespace prefixes in deployer sources

---

logging/LoggingService.cpp

The order of member initializers should match the declaration order in the header, which is also the order of construction. The new members were added in https://github.com/orocos-toolchain/ocl/pull/60.

Fix compiler warning about the order of member initializers in OCL::LoggingService constructor

---

logging/Appender.cpp
logging/FileAppender.cpp
logging/OstreamAppender.cpp
logging/RollingFileAppender.cpp
lua/rtt.cpp
reporting/ReportingComponent.cpp
reporting/TcpReporting.cpp
reporting/socket.cpp
reporting/socket.hpp
taskbrowser/TaskBrowser.cpp

Counterpart of https://github.com/orocos-toolchain/rtt/pull/317 for OCL.
Only misleading whitespace (`-Wmisleading-indentation`), redundant semicolons and one usage of deprecated `auto_ptr`.

Fix compiler warnings with GCC 9

---

logging/Category.cpp
logging/Category.hpp

Make `OCL::logging::Category::debug(RTT::rt_string const&)`, `info`, etc... uses `log(log4cpp::Priority, RTT::rt_string const&)` so it can be overriden.
Closes #91.

Allow OCL::logging::Category to be property overriden
